title: "esq.io"
repo: "https://github.com/vzvenyach/vzvenyach.github.io"

markdown: kramdown

collections:
    blog:
        output: true
        permalink: "blog/posts/:title/"

    drafts:
        output: true
        permalink: "blog/drafts/:title/"

    pages:
        output: true
        permalink: "pages/:path.html"
