title: "esq.io"
repo: "https://github.com/vzvenyach/vzvenyach.github.io"

markdown: kramdown

collections:
    blog:
        output: true
        permalink: "blog/posts/:title/"
    pages:
        output: true
        permalink: "pages/:path.html"
