baseURL = "https://vdavez.com/"
footnoteReturnLinkContents = "↩"
enableInlineShortcodes = true
title = "Dave Zvenyach's website"
theme = "PaperMod"

enableEmoji = true
rssLimit = 20
timeZone = "America/Chicago"
enableRobotsTXT = true
enableGitInfo = true

[pagination]
  pagerSize = 20

[build]
  writeStats = true

[params]
  AuthorName = "V. David Zvenyach"
  GitHubUser = "vdavez"
  description = "A website created by V. David Zvenyach"
  images = ["images/Zvenyach.jpg"]
  title = "Dave Zvenyach's website"
  
  # SEO enhancements
  keywords = ["law", "technology", "government", "procurement", "writing"]
  author = "V. David Zvenyach"
  
  # Social metadata
  linkedin = "vdavez"
  
  # Performance settings
  env = "production"
  
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[permalinks]
  posts = "/:year/:month/:slug/"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIdType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "github"
    tabWidth = 4

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.html]
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 0
    [minify.tdewolff.json]
      precision = 0
    [minify.tdewolff.svg]
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10m"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "10m"
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "720h"
