baseURL = "https://esq.io/"
footnoteReturnLinkContents = "↩"
enableInlineShortcodes = true
title = "esq.io"

[params]
  AuthorName = "V. David Zvenyach"
  GitHubUser = "vzvenyach"
  description = "A website created by V. David Zvenyach"
  images = ["images/bronzefonze.jpg"]
  title = "Dave Zvenyach's Website"

[permalinks]
  posts = "/:year/:month/:slug/"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
