baseURL = "https://vdavez.com/"
footnoteReturnLinkContents = "↩"
enableInlineShortcodes = true
title = "Dave Zvenyach's website"

enableEmoji = true
rssLimit = 10
timeZone = "America/Chicago"

paginate = 20

[build]
  writeStats = true


[params]
  AuthorName = "V. David Zvenyach"
  GitHubUser = "vdavez"
  description = "A website created by V. David Zvenyach"
  images = ["images/Zvenyach.jpg"]
  title = "Dave Zvenyach's website"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]

[build]
  writeStats = true

[permalinks]
  posts = "/:year/:month/:slug/"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
      mathjax = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-light"
    tabWidth = 4
