[build]
    publish = "public"
    command = "hugo --gc --minify"

[build.environment]
    HUGO_VERSION = "0.98.0"
    NODE_VERSION = "18.1.0"

[context.production.environment]
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
    HUGO_BASEURL = "https://esq.io/"
